package com.stellarflux.ui.theme

import androidx.compose.ui.graphics.Color

// Dark theme (myclaw.ai dark — deep navy)
val DarkBackground = Color(0xFF050810)
val DarkSurface = Color(0xFF0A0F1A)
val DarkSurfaceVariant = Color(0xFF111827)
val DarkSurfaceHigh = Color(0xFF1A1F2E)
val DarkOnBackground = Color(0xFFF0F4FF)
val DarkOnSurface = Color(0xFFF0F4FF)
val DarkOnSurfaceVariant = Color(0xFF8892B0)
val DarkPrimary = Color(0xFFFF4D4D)
val DarkOnPrimary = Color(0xFFFFFFFF)
val DarkSecondary = Color(0xFF8892B0)
val DarkOutline = Color(0xFF1E2538)
val DarkError = Color(0xFFFF4D4D)

// Light theme (myclaw.ai light — neutral grays)
val LightBackground = Color(0xFFF4F4F5)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFE4E4E7)
val LightSurfaceHigh = Color(0xFFD4D4D8)
val LightOnBackground = Color(0xFF18181B)
val LightOnSurface = Color(0xFF3F3F46)
val LightOnSurfaceVariant = Color(0xFF71717A)
val LightPrimary = Color(0xFFEF4444)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightSecondary = Color(0xFF71717A)
val LightOutline = Color(0xFFE4E4E7)
val LightError = Color(0xFFEF4444)
